// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need prepared-statement support, which the transaction-mode
    // pooler (DATABASE_URL, port 6543) doesn't have — DIRECT_URL keeps
    // migrate/db-push on the session-mode connection (port 5432) instead.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
